spring:
    datasource:
        url: jdbc:h2:file:./src/main/resources/db/appdb
        driverClassName: org.h2.Driver
        username: sa
        password: sa
    h2:
        console.enabled: true
        console:
            path: /h2-console
            settings.trace: false
            settings.web-allow-others: false
    jpa:
        properties:
            hibernate:
                ddl-auto: update

