POST http://localhost:8080/usuarios
Content-Type: application/json

{
    "nome": "Marcio Costa",
    "email": "marcio@gmail.com",
    "localizacao": "Fortaleza, CE"

}

###
GET http://localhost:8080/usuarios
Content-Type: application/json
